#!/bin/sh

set -v
set -x
if [ -e Makefile ]
then
	make distclean
fi
rm -f *.cache *.m4
rm -f config.log config.status
#rm -f config.guess config.sub depcomp ltmain.sh
#(cat m4/*.m4 > acinclude.m4 2> /dev/null)
cp INSTALL INSTALL.bak
autoreconf --verbose --install --force $@
mv INSTALL.bak INSTALL
#./configure
