.TH J-PILOT 1 "November 22, 2005"
.SH NAME
jpilot \- A palm pilot desktop for Linux/Unix
.SH SYNOPSIS
.B jpilot [-v] [-h] [-d] [-a] [-A] [-i] [-s]
.SH "DESCRIPTION"
J-Pilot is a desktop organizer application for the palm pilot and other
Palm OS devices.  It is similar in functionality to the one that
3Com/Palm distributes.
.SH OPTIONS
.TP
.B \-v
displays version and exits.
.TP
.B \-h
displays help and exits.
.TP
.B \-d
displays debug info to stdout.
.TP
.B \-a
ignores missed alarms since the last time program was run.
.TP
.B \-A
ignores all alarms, past and future.
.TP
.B \-i 
makes 
.B jpilot
iconify itself upon launch.
.TP
.B \-s 
initiates a sync on the running
.B jpilot
instance.

If you have more than one 
.B jpilot 
running at the same time the sync may
not work as expected since nothing is done to support a multi-instance
configuration.
.SH ENVIRONMENT
The PILOTPORT and PILOTRATE environment variables are used to specify
which port to sync on and at what speed.

If PILOTPORT is not set then it defaults to /dev/pilot.
.SH BUGS
See @DOCDIR@/BUGS
.SH SEE ALSO
jpilot-sync(1)
.SH AUTHOR
Judd Montgomery <judd@jpilot.org>
