.TH JPILOT-DUMP 1
.SH NAME
jpilot-dump \- A command line tool for dumping jpilot databases.
.SH SYNOPSIS
.B jpilot-dump
[ options ]
.SH DESCRIPTION
Dump jpilot databases.
.SH OPTIONS
.TP
.B \+B \+M \+A \+T
format like date +format.
.TP
.B \-v
displays version and exits.
.TP
.B \-h
displays help and exits.
.TP
.B \-f
displays help for format codes.
.TP
.B \-D
dump DateBook.
.TP
.B \-N
dump appts for today in DateBook.
.TP
.BI "\-N" YYYY/MM/DD
dump appts on YYYY/MM/DD in DateBook.
.TP
.B \-A
dump Address book.
.TP
.B \-T
dump Todo list as CSV.
.TP
.B \-M
dump Memos.
.SH BUGS
See /usr/share/doc/jpilot/BUGS
.SH SEE ALSO
jpilot(1)
.SH AUTHOR
September 2001 jpilot-dump 0.98-1 Copyright (C) hvrietsc@yahoo.com.

Manpage by Pablo Averbuj <pablo@debian.org>, updated Ludovic Rousseau
<rousseau@debian.org>

