.TH JPILOT-MERGE 1 "April 6, 2011"
.SH NAME
jpilot-merge \- merge an unsynced records file (pc3) into the corresponding palm database (pdb) file
.SH SYNOPSIS
.B jpilot-merge {input pdb file} {input pc3 file} {output pdb file}
.SH "DESCRIPTION"
This program will merge an unsynced records file (pc3) into the
corresponding palm database (pdb) file.
.P
WARNING: Only run this utility if you understand the consequences!
.P
The merge will leave your databases in an unsync-able state.
It is intended for cases where J-pilot is being used as a standalone PIM
and where no syncing occurs to physical hardware.
.P
WARNING: Make a backup copy of your databases before proceeding.
.P
It is quite simple to destroy your databases by accidentally merging
address records into datebook databases, etc.
.SH SEE ALSO
jpilot(1)
