.TH JPILOT-DIAL 1 "November 22, 2005"
.SH NAME
jpilot-dial \- generates the DTMF tone signals used for telephone dialing
.SH SYNOPSIS
.B jpilot-dial
.RI [ options ] " number" ...
.SH DESCRIPTION
This manual page briefly documents the
.B jpilot-dial
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.B jpilot-dial
generates the DTMF tone signals used for telephone
dialing and by default sends the signals to the sound card.

It can be used for easy dialing, simply put the telephone
microphone near the computer speaker and let the software
dial for you.

It is intended for dialing from within database programs that
also store telephone numbers.
.SH OPTIONS
.TP
.B \-\-tone\-time
milliseconds, default 100
.TP
.B \-\-silent\-time
milliseconds, default 50
.TP
.B \-\-sleep\-time
milliseconds, default 500
.TP
.B \-\-output\-dev
default 
.I /dev/dsp
.TP
.B \-\-use\-audio
default 1
.TP
.B \-\-bufsize
default 4096
.TP
.B \-\-speed
default 8000
.TP
.B \-\-bits
default 8
.TP
.B \-\-lv
left speaker volume
.TP
.B \-\-rv
right speaker volume
.TP
.B \-\-table\-size
default 256
.TP
.B \-\-volume
default 100
.TP
.B \-\-left
default 0
.TP
.B \-\-right
default 0
.SH SEE ALSO
.BR jpilot (1)
.br
.SH AUTHOR
This manual page was written by Ludovic Rousseau <rousseau@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
