.TH J-PILOT 1
.SH NAME
jpilot \- A palm pilot desktop for Linux/Unix
.SH SYNOPSIS
.B jpilot
.SH "DESCRIPTION"
J-Pilot is a desktop organizer application for the palm pilot and other
Palm OS devices.  It is similar in functionality to the one that
3Com distributes.
.SH BUGS
See /usr/share/doc/jpilot/BUGS
.SH SEE ALSO
jpilot-sync(1), jpilot-upgrade-99(1)
.SH AUTHOR
Judd Montgomery <judd@jpilot.org>
