.TH JPILOT-MERGE 1 "April 6, 2011"
.SH NAME
jpilot-merge \- merge an unsynced records file (pc3) into the corresponding palm database (pdb) file
.SH SYNOPSIS
.B jpilot-merge {input pdb file} {input pc file} {output pdb file}
.SH "DESCRIPTION"
This program will merge an unsynced records file (pc3) into the
corresponding palm database (pdb) file.
.P
Only run it if you know what you are doing!!!
.P
This will leave your databases in an unsync-able state.  It is possible
to merge address records into datebook, etc., you do not want to do
this!!!
.SH SEE ALSO
jpilot(1)
